### ISSUE TITLE
Rules update failed

### ISSUE THREAD

**Issue by borjaevo** [tlhackque/BlockCountries#14]
I tried to run BlockCountries in a debian 7 server.

Starting blocked countries IP filter:
Updated IP zone data from apnic
Updated IP zone data from lacnic
Updated IP zone data from afrinic
Updated IP zone data from ripe
Updated IP zone data from ariniptables-restore: line 11365 failed
Rules update failed: exit code 1 at line 0
[FAILED]

Not sure if i done something wrong.

Thanks.

**Comment by tlhackque** [comment]
This is most likely either an old version of iptables or a configuration issue.

To gather enough data to understand this, please do the following two things:
a) run `bcinstall`  & post the output
b) use
`BlockCountries start -d -z 2>debug.zip`
Post the `.zip` file

The `.zip` file contains fairly detailed configuration data.  If you consider it sensitive, post it on a password-protected webpage & e-mail me the access information.  (my gitub user name at yahoo.com will work.)

**Comment by borjaevo** [comment]
This is the output of bcinstall:

bcinstall version 2.97

Perl version 5.14.2 was found in /usr/bin

  Checking Perl module status

All needed perl modules are installed and meet minimum version requirements

Checking iptables installation

iptables version v1.4.14 installation validated

Inspecting configuration of ./BlockCountries

  Configuration file search list:
    Directory               File           Status
    $ENV{BlockCountriesCFG}                [Not present]
    .                                      [Not checked, runtime value unknown]
    ~                                      [Directory exists, assuming runtime /root]
    /etc/sysconfig                         [Not present]
    /etc/default            BlockCountries [Exists]
    /etc                                   [Directory exists]

  The first file found will be used at runtime.
  Use BlockCountries config to determine which file is selected.

All checks completed successfully by bcinstall v2.97

Thanks

**Comment by borjaevo** [comment]
How i have to write list of countries in config file. I put 2 countries (2 ISO codes) in different lines. Maybe i have to separate with commas? Could this be the issue?

Thanks.

**Comment by tlhackque** [comment]
Thank you for bcinstall output.  Please provide the .zip.

No commas are required (or accepted).

**Comment by tlhackque** [comment]
For reference, the `BlockCountries` in the config/ directory is a working configuration file that illustrates the configuration file syntax.  Of course, it does need to be modified for your needs. (at a minimum file paths and countries to block.)

**Comment by borjaevo** [comment]
Yes, i modified country list. 

I send you debug file. Thanks.

**Comment by tlhackque** [comment]
You seem to have some other software that is trying to block countries using iptables; you have a very large iptables chain called "countrydrop".  But that chain is not in use.  This doesn't explain your problem, but it is a waste of memory.  You should disable or remove the software that generated it.  To remove of these rules, use
`iptables -F countrydrop`
`iptables -X countrydrop`

With respect to `BlockCountries`:

You may need -conntrack in your config file.  (This will be automatically detected in the next release.)  

To determine whether this is the problem, execute the following commands & provide the output:
````
iptables -N test-chain
iptables -A test-chain -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
iptables -nvL test-chain
iptables -F test-chain
iptables -X test-chain
````
You may see an error message; continue with the commands.
If you see a line like this:
`    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           ctstate RELATED,ESTABLISHED`
then you must add `-conntrack` to the config file.

Otherwise, I'll have to look further.

Also, I would appreciate the output of  `/sbin/ifconfig`.  The debug data collection is confused by what's generated on your system.  I'd like to fix that.

**Comment by borjaevo** [comment]
Ok, I cant test it right now. But I send you results soon. 
Yes I have other chain from bash script you discussed on nixcraft but I prefer your script. 
Sorry for newbie question. But what - conntrack does? 

Thanks

**Comment by tlhackque** [comment]
It's a perfectly reasonable question.

-conntrack is documented in the help.  It changes how certain rules are generated.  iptables made a change in how those rules are specified.  Some versions of iptables use a module called "state" while others use "conntrack" for the same function.  

Some versions of iptables accept either; some only one; some generate warnings with one and not with the other.  Linux distributions are not consistent about this; some use iptables as provided from the upstream; others patch it (typically for compatibility).  And of course, they package different base versions.

-conntrack tells BlockCountries to use the "conntrack" module syntax.  The default generates "state" syntax.

The little test that I suggested will tell me which one your system supports.

In the current BlockCountries, you have to figure this out by experimentation.  In the next version, bcinstall will automate this.

**Comment by borjaevo** [comment]
You're right. The output is like you said:

:~# iptables -nvL test-chain   
Chain test-chain (0 references)                  
 pkts bytes target     prot opt in     out     so
urce               destination                   
    0     0 RETURN     all  --  *      *       0.
0.0.0/0            0.0.0.0/0            ctstate R
ELATED,ESTABLISHED  

So I need to add - conntrack
Where in config file should I place - conntrack? 
Thanks

**Comment by tlhackque** [comment]
It doesn't matter where in the file you put -conntrack, as long as you don't  put it between another switch and its value.  So the first line of the configuration file would be fine.

As I mentioned previously, I would appreciate the output of `/sbin/ifconfig >ifconfig.txt` so that I can find out why the debug data is not collected properly on your machine.

**Comment by borjaevo** [comment]
Hello,

I tried with -conntrack in config file. But it does not work. Same error that first post. 

I send you ipconfig tomorrow. 

Thanks.

**Comment by tlhackque** [comment]
That is very strange.  The error indicates a problem with loading the generated rules for IPv4.  Unfortunately, the `iptables-restore` utility (which `BlockCountries` runs) does not provide very helpful error messages.

I built a x86-64  Debian 7 (virtual) machine from the network distribution & installed the released version of `BlockCountries`.  I updated/installed Perl modules (per `bcinstall`).

I extracted the ruleset generated by `BlockCountries` on your system from the debug data that you supplied, and verified that it loads successfully with `iptables` v1.4.14.  This is the same version that you have.  It accepts, but does not require  `-conntrack`.

So the rules are good.  And the distribution's `iptables-restore` and kernel can load them.

I also restored the rather strange `iptables` environment reported in the debug data.  You have a number of unusual `iptables` tables active, but empty (`security,raw,nat,mangle`) Do you have other software  installed that is using iptables? I included the `countrydrop` rules.

I installed your configuration file (the one without -conntrack).

`BlockCountries start` succeeds. There are no error messages. (note that -update is not necessary at this point, since the IP address assignments for ru and ua have been cached).  So the problem isn't in `BlockCountries` itself.  And standard Debian is OK.

`uname` shows that my kernel version is 3.2.0-4-amd64, which is the latest Debian 7.11.  But yours is 3.10.15-20131009a.
````
cat /etc/debian_version
7.11
apt-cache search linux-image | grep -P 'image-.*64 - Linux'
linux-image-3.2.0-4-amd64 - Linux 3.2 for 64-bit PCs
linux-image-3.2.0-4-rt-amd64 - Linux 3.2 for 64-bit PCs, PREEMPT_RT
linux-image-2.6-amd64 - Linux for 64-bit PCs (dummy package)
linux-image-amd64 - Linux for 64-bit PCs (meta-package)
linux-image-rt-amd64 - Linux for 64-bit PCs (meta-package), PREEMPT_RT
````

Where did your kernel come from?  Did you build it yourself?  Download if from a non-standard repository?  (kernel modules receive the rules.)

Are there any messages in the system log files at the time that you run `BlockCountries start`?

Have you enabled SeLinux?  If so, it may be preventing iptables from running.  Please provide output from `audit2allow -lb` and `getenforce` `BlockCountries` does work with SeLinux on Fedora, but no one has reported trying it on Debian.  

if `getenforce` returns `Enabled', try `setenforce 0` before running `BlockCountries`.  Then `setenforce 1`.  If that works, provide the output of `audit2why`.

Let's see if you have a patched (or corrupt) version of the iptables utilities:
````
md5sum -b /sbin/ip*tables*
73482167c2ef1f1ef6919c5c12a0c3d6 */sbin/ip6tables
73482167c2ef1f1ef6919c5c12a0c3d6 */sbin/ip6tables-restore
73482167c2ef1f1ef6919c5c12a0c3d6 */sbin/ip6tables-save
73482167c2ef1f1ef6919c5c12a0c3d6 */sbin/iptables
73482167c2ef1f1ef6919c5c12a0c3d6 */sbin/iptables-restore
73482167c2ef1f1ef6919c5c12a0c3d6 */sbin/iptables-save
````

**Comment by borjaevo** [comment]
Hello,

Yes, i think the software has created the empty tables is webmin. Maybe, in some way, is also blocking the loading of IPv4 rules. 
Im going to check messages in log files and report to you. About SeLinux, IPtables is running, i'm rejecting some IPs and is working well. 
Im not very convinced about disabling selinux, this is a production server. Maybe is better that i try to clone the machine in a VM and test this.

Thanks.

**Comment by tlhackque** [comment]
In the debug data that you sent, iptables has NO active rules.  The `countrydrop` rules exist, but are not in any chain.  `iptables -nvL` produced:

````
Current IPv4 rules
------------------

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
````

I'm not suggesting that you permanently disable SeLinux.  setenforce only sets permissive mode; it doesn't do anything permanent.  Just set permissive mode long enough to run BlockCountries once.  This will tell us if this the issue.

As I mentioned, I have created a Debian 7.11 machine from scratch.  BlockCountries works.  The rules generated on your system work.  The one difference that I have found is your kernel version.  If you can tell me where your obtained your kernel, I can try that here.

Or, if you clone the system & can reproduce the problem on the clone, I can investigate on the clone.  (I will not login to a production machine.)  I can provide an SSH public key via e-mail if you wish to take this route.  I have your e-mail address.

**Comment by tlhackque** [comment]
I have updated my virtual machine to kernel 3.16.0-0.bpo.4-amd64 (wheezy-backport), and verified that `BlockCountries` works with your configuration (with and without `-conntrack`). I recommend `-conntrack` as it's the newer function in `netfilter`.

````
# uname -a
Linux debutante 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.39-1+deb8u1~bpo70+1 (2017-02-24) x86_64 GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
# BlockCountries-2.22-Release/BlockCountries start
Starting blocked countries IP filter:                      [ OK ]

# Note: the INPUT chain shows a call to BlockCountries (BLOCKCC1 may be replaced by BLOCKCC0)
#       It would also have your firewall's rules.

#  iptables -nvL | grep -A15 INPUT
Chain INPUT (policy ACCEPT 139 packets, 13844 bytes)
 pkts bytes target     prot opt in     out     source               destination
  139 13844 BLOCKCC1-I  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 70 packets, 9392 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain BLOCKCC1-DLOG (8907 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            limit: avg 1/min burst 10 LOG flags 0 level 4 prefix "[Blocked CC]:"
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain BLOCKCC1-I (1 references)

````
I couldn't find a 3.10 kernel for Wheezy, but this shows that BlockCountries works with kernels both older and newer than yours.

Of course, we don't know if it's a kernel issue.  But there's nothing more that I can do without the ability to reproduce your issue.

I also enabled SeLinux & verified that BlockCountries works and does not generate any AVCs.

Any messages from your log files would be helpful.

Also, despite the GUI screenshot from your firewall configuration, there were no active rules.   This either means that it also failed to load its iptables rules, or something removed them.  (BlockCountries did not.)

If your firewall can't load it's rules, neither can BlockCountries.

I suggest fixing that problem first, as I don't believe BlockCountries is at fault.  When `iptables -nvL` shows your firewall rules, run `BlockCountries start -d -z 2>debug.zip` so we can see what's really happening.  The debug output shows the full state of iptables rules before BlockCountries does anything to them.

**Comment by borjaevo** [comment]
Iptables -nvL shows firewall rules now. I send you debug file again soon.

**Comment by tlhackque** [comment]
After considerable off-line analysis, we determined that the problem is an incomplete or corrupt version of `iptables`.  Specifically, (at least) the `limit` and `multiport` modules are not present and can't be loaded - either by `iptables,` by `iptables-restore,` or by `modprobe`.

The system is using a kernel not from a standard Debian distribution nor built by you.

An empty `lsmod` tends to indicate that this is a VPS, which is not exporting the kernel module library nor loading these modules into the kernel.

Resolution will require you to contact the kernel (perhaps hosting) provider.  Be aware that configuration changes and/or `BlockCountries` updates may require additional `netfilter` modules.  The hosting provider of a VPS may not wish to load all possible modules.  So this may be an on-going issue.

In any case, this is not a `BlockCountries` issue.

To make troubleshooting similar systems easier for future users, a test for this misconfiguration of `iptables` is in the next major release of `bcinstall`.

**Comment by tlhackque** [comment]
@borjaevo reports that after installing a standard Debian kernel, `BlockCountries` works as expected.  This confirms the diagnosis.

The host is not a VPS (it is a leased dedicated server from a hosting provider), but it did use a custom kernel that included a subset of `iptables` that is not sufficient for `BlockCountries` and does not support loadable modules.

The delay was due to the time required to find a maintenance window for the kernel installation.

**Comment by borjaevo** [comment]
First of all i just want to thank Tim for helping me, it was a long journey and he help me even with some questions not directly related with BlockCountries, he has shown great knowledge and patience.

Like Tim said problem was minimal kernel i have installed before, i confirm after upgrading kernel BlockCountries work as expected. Its been used for some days now and works very well.
